### PR TITLE
Product Review screens

### PR DESCRIPTION
**Pull request by abdullahs**
Functionality to add product review

### CODE REVIEW

**Comment by jonesde** [comment]
A few comments:

1. since this is your first contribution to PopCommerce please add your name to the AUTHORS file, either with the first pull request or as a separate one
2. formatting: indent with 4 spaces, don't use tabs
3. a better place for the ProductReviewList screen would be under the Product/Detail screen, in other words in a directory called "Detail" instead of "Review"; this organizes it more naturally and chances are there will be other screens used in the product detail screen over time
4. there are some log actions still in place, please remove those
5. don't specify the productStoreId, it is already set in the PopCommerceRoot screen (currently it is set to a constant, but that will change when multi-store support is more fully implemented)
6. It would be helpful to add some demo data with a few reviews on one or two products for easier testing

That's all I notice for now. Please make the needed changes and submit a new pull request.

**Comment by abdullahs** [comment]
Should the product review demo data go in mantle's ZzcProductDemoData.xml ?

**Comment by jonesde** [comment]
Yes, good point, that would be the best place to put it.

**Comment by abdullahs** [comment]
Created pull request #12

**Pull request closed without merging**
