### PR TITLE
Escape the term used in getProductList transition.

### PR DESCRIPTION
**Pull request by chunlinyao**

### CODE REVIEW

**Comment by jonesde** [comment]
After merging the pull request in Moqui for escapeElasticQueryString() I reconsidered this... escaping the string from the user makes it look for literal terms only and none of the of extra functionality in elastic search strings would be available, so this is a bad idea unless the search is meant to be only very simple (maybe the case for certain public facing apps, but not for admin ones). Users will need some documentation about how to structure search strings, including how to escape values, and that is a far better (more powerful, useful, etc) solution than escaping all special ES/Lucene chars and disabling various search features.

**Comment by chunlinyao** [comment]
Yes, we should allow users input complex elastic search strings in some place. But in this case the text line shows “Product Name [product id]”. When I click it and press a backspace key the error occurs.

**Comment by jonesde** [comment]
Been thinking about this issue: if we allow the full search syntax to be used an invalid syntax is always possible and the best we can do is handle the error in a clean way. If that approach sounds adequate is this still an issue, or should we change something to handle the error more cleanly?

**Comment by chunlinyao** [comment]
Yes, If we can handle invalid syntax in a clean way that will not be a issue. The only thing remained is determine where should allow the full syntax, and where the literal term is ok.
Maybe we can allow full syntax and if invalid fallback to literal terms. Just like google, google also has a search syntax, But it never complain about syntax error.

**Pull request closed without merging**
