### PR TITLE
Add persistent display of screen subject above tabs.

### PR DESCRIPTION
**Pull request by JWager-rch**
Display screen subject (party, facility, etc.) that persists when changing tabs.

### CODE REVIEW

**Comment by jonesde** [comment]
This is a good start, here are some ways it can be improved:

1. Instead of using inline expressions like "${partyId} - ${displayName}" use the existing *NameTemplate l10n values for consistency and so such labels may be changed by changing a database record (see the MantleUdmSetupData.xml file, the moqui.basic.LocalizedMessage records with locale="default"); use the text-map attribute on the label element to specify a Map, or EntityValue which implements the Map interface, to use when expanding the text to display (see example below)
2. for entities with a pseudoId or short name use that instead of the internal ID, ie Party.pseudoId instead of Party.partyId; using the *NameTemplate values instead of inline expressions as described above will take care of this
3. code size and logic can be dramatically reduced using Groovy features like the 'Elvis' operator which is a collapsed trinary used for defaults (ie firstName ? firstName : '' => firstName ?: ''); again, the *NameTemplate approach will take care of this
4. all **label** elements on these tab sets need a condition attribute so they do not display when there is no data to display, this is especially important so the Find* and other screens are under the tab set wrapper screen (like FindParty under Party.xml) and the labels should not be displayed at all on those

Here is an example of how the actions and widgets would look on the Party.xml screen:

```
    <actions>
        <entity-find-one entity-name="mantle.party.PartyDetail" value-field="partyDetail"/>
    </actions>
    <widgets>
        <label text="PartyNameTemplate" text-map="partyDetail" type="strong" condition="partyDetail"/>
        <subscreens-panel id="PartyPanel" type="tab"/>
    </widgets>
```

This is a fairly common pattern for labels, links, etc using text + text-map + condition. Note that I also changed it from type="h3" to type="strong" so that it is bold but not so big and without so much white space. I'm thinking of changing the framework to support a label inside a tab bar to the right of the tabs to use that currently empty space, but for now plain type="strong" with a label above seems adequate.

**Comment by JWager-rch** [comment]
This is along the lines of the sort of response I expected. I had the
feeling that my approach might not be universal enough.

We had touched on the templates early on, but I moved away from them
because some of the displays I wanted didn't seem to have pre-built
templates. Looking at them again, I see that, of the nine screens I've
changed, five of them can probably be covered by existing templates. I will
make those changes and test them out.

Of the other four, two of them have templates that are close, but not the
same as what I built on the screens, and two of them don't seem to have
anything built currently. Would you suggest that I create the missing
templates?

Also, one of the screens,
SimpleScreens/screens/SimpleScreens/Asset/Asset.xml, built its display with
data from both the asset and the product entities. How would I build a
combined text-map from multiple data sources?

**Comment by jonesde** [comment]
In general I'd say use existing *NameTemplate values when close. For those that have nothing similar there is likely little benefit to adding a l10n record, unless a similar template is used in a few places.

As for particular ones that don't match, you didn't mention any in particular or what the differences are, etc. To comment on that I'd have to review your full patch against the existing LocalizedMessage records and then guess at what you have in mind, you're sort of asking me to do a diff you've already done. Ask a more specific question or request for comment and I'll see what I can do, but I prefer not to guess, it is rarely helpful.

In another review of some of this one thing I noticed in the Order.xml screen is a hard-coded reference to the partyId 'Company'. What is that? It looks like you're trying to determine if the order is a sales order or a purchase order. In a multi-organization system that is not so simple, especially with orders where multi-party orders are partially supported (ie with the Vendor and Customer specified for each OrderPart). For now the order screens are somewhat simplified and don't support fully multi-party orders so you can look at the first OrderPart for Vendor and Customer, and you can follow the existing logic in the mantle.order.OrderInfoServices.get#OrderDisplayInfo service based on looking for the OrgInternal role for Vendor or Customer.

For a combined Map for expansion you can get fancy in Groovy using the '+' operator on two Maps to create a new one with the contents of both, or explicitly create a Map and call putAll() on it for each of the two maps to create a combined Map.

**Comment by JWager-rch** [comment]
Screens for which no templates exist:
- ProductStore.xml under SimpleScreens
- Shipment.xml under PopCommerceAdmin
If we don't want to create a new template, should I just leave those as
currently coded? (I probably should change the formatting to match the
others)

Screens that don't match:
- Asset.xml under SimpleScreens
    The AssetNameTemplate contains the assetName field, but my testing
shows only the assetID and nothing for the assetName - as in the column
isn't populated? My version used the assetID to pull the name from the
product. This is where my desire to use data from two maps came from.
    Side note: Getting fancy (or anything else) with Groovy and creating
Maps is well outside my current skill set, so, no, I can't.
- Order.xml under PopCommerceAdmin
    The OrderNameTemplate, despite its name, only contains the orderId.

More on Order.xml:
That is the screen I was concerned about in particular about not being
universally applicable outside of the Ridgecrest setup. Since Purchase and
Sales orders are stored together, I was attempting, as you suspected,  to
tell them apart to determine which of the partyId's to use to pull the
name. The OrgInternal role seems like a better approach. Are you suggesting
that I call the service and use the returned boolean to look up the party,
or that I replicate the service logic in place and use logic similar to
what I have there now to look up the partyName after I determine which
partyId to use?

**Comment by jonesde** [comment]
On the screens with no existing templates: yes, just leave the inline stuff. On the Shipment.xml screen I don't see much point in displaying the toPartyId, that is an internal ID that may be different from the typically displayed and possibly different pseudoId (a separate ID, or 'short name' for a Party). I don't know what sort of design you're working against or if you just have general direction and are designing on the fly, but IMO basic text like "Shipment ${shipmentId}" is probably adequate.

While it might make sense to show more for Shipment and Order they are really only identified by an ID. There is a concept of an order description but it is rarely used.

For Asset.xml yes it's fine to show Asset and Product data. You don't need to combine the Map and use the text-map attribute, you can just use Groovy's dot syntax to access map entry values. For example instead of:

<label text="${productName}" text-map="product"/>

you can use:

<label text="${product.productName}"/>

Note that Groovy also has a 'safe' dot operator to evaluate to null instead of throwing a NullPointerException and it is just '?.' instead of '.'. To use this with the above you'd have something like "${product?.productName}". Note that if the value is null it will evaluate to a String value of "null" instead of "" (empty string). To avoid displaying "null" for missing values you can use Groovy's 'Elvis' operator which is a collapsed trinary (if and then expressions match), like: "${product?.productName ?: ''}".

There are many things in Groovy like these that make life easier, that's part of why we use it in Moqui. They are used a lot in OOTB services, screens, etc so one way or another when working with Moqui it will be helpful to know about them.

On the Order.xml screen: no, don't call that service as it does a lot of work (dozens of queries and a fair amount of data processing), I referenced it as a resource where you can see how it determines purchase vs sales orders.

**Comment by JWager-rch** [comment]
Your Groovy examples don't appear to have come through in the comment.
Would you please reproduce them?

**Comment by jonesde** [comment]
> Your Groovy examples don't appear to have come through in the comment. Would you please reproduce them?

Done

**Comment by jonesde** [comment]
This is looking much better. IMO it's fine to go in as it is now, a good first pass, and given that these will likely be reviewed, tweaked, and improved over time.

The main thing left to do is for you to sign the AUTHORS file, in both sections (CC0 and Patent Disclaimer), and both here in PopCommerce and in the related pull request in SimpleScreens. For more information see the IP section of the Issue and Pull Request Guide:

https://moqui.org/m/docs/moqui/Issue+and+Pull+Request+Guide#intellectual-property

**Pull request merged**
